// Generated by CoffeeScript 2.3.2
(function() {
  var async, defaults, fg, handleFiles, handleOpts, join, parse, relative, sep, sync;

  fg = require('fast-glob');

  ({relative, join, parse, sep} = require('path'));

  defaults = {
    extensions: ['js', 'ts', 'coffee', 'json']
  };

  handleFiles = function(dir, files) {
    var currentObject, file, i, j, len, len1, object, parsed, token, tokens;
    object = {};
    for (i = 0, len = files.length; i < len; i++) {
      file = files[i];
      parsed = parse(file);
      tokens = relative(dir, parsed.dir).split(sep);
      currentObject = object;
      for (j = 0, len1 = tokens.length; j < len1; j++) {
        token = tokens[j];
        if (!token) {
          continue;
        }
        currentObject = currentObject[token] != null ? currentObject[token] : currentObject[token] = {};
      }
      currentObject[parsed.name] = require(join(process.cwd(), file));
    }
    return object;
  };

  handleOpts = function(opts) {
    if ('string' === typeof opts) {
      return {
        dir: opts
      };
    }
    return opts;
  };

  sync = function(opts) {
    var dir, extensions;
    ({dir, extensions = defaults.extensions} = handleOpts(opts));
    return handleFiles(dir, fg.sync(join(dir, `**/*.{${extensions.join(',')}}`)));
  };

  async = async function(opts) {
    var dir, extensions;
    ({dir, extensions = defaults.extensions} = handleOpts(opts));
    return handleFiles(dir, (await fg.async(join(dir, `**/*.{${extensions.join(',')}}`))));
  };

  module.exports = {sync, async};

}).call(this);
